//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.XpressNetLi.Comunication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Answers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Answers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flake.MoBa.XpressNetLi.Comunication.Resources.Answers", typeof(Answers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast All Locomotives Off was sent..
        /// </summary>
        internal static string BCAllLocosOffDesc {
            get {
                return ResourceManager.GetString("BCAllLocosOffDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast: All locomotives off.
        /// </summary>
        internal static string BCAllLocosOffName {
            get {
                return ResourceManager.GetString("BCAllLocosOffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast All Off was sent..
        /// </summary>
        internal static string BCAllOffDesc {
            get {
                return ResourceManager.GetString("BCAllOffDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcasr: All Off.
        /// </summary>
        internal static string BCAllOffName {
            get {
                return ResourceManager.GetString("BCAllOffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast All On was sent..
        /// </summary>
        internal static string BCAllOnDesc {
            get {
                return ResourceManager.GetString("BCAllOnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast: All On.
        /// </summary>
        internal static string BCAllOnName {
            get {
                return ResourceManager.GetString("BCAllOnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast Program Mode was sent..
        /// </summary>
        internal static string BCProgramModeDesc {
            get {
                return ResourceManager.GetString("BCProgramModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast: Programm mode.
        /// </summary>
        internal static string BCProgramModeName {
            get {
                return ResourceManager.GetString("BCProgramModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consists info about central state..
        /// </summary>
        internal static string CentralStateInfoDesc {
            get {
                return ResourceManager.GetString("CentralStateInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central state info.
        /// </summary>
        internal static string CentralStateInfoName {
            get {
                return ResourceManager.GetString("CentralStateInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCP-Central (Compact or Commander).
        /// </summary>
        internal static string CentralTypeDCP {
            get {
                return ResourceManager.GetString("CentralTypeDCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LH 200 Central.
        /// </summary>
        internal static string CentralTypeLH200 {
            get {
                return ResourceManager.GetString("CentralTypeLH200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZ 100 Central.
        /// </summary>
        internal static string CentralTypeLZ100 {
            get {
                return ResourceManager.GetString("CentralTypeLZ100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains version of central connected to interface..
        /// </summary>
        internal static string CentralVersionInfoDesc {
            get {
                return ResourceManager.GetString("CentralVersionInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of central.
        /// </summary>
        internal static string CentralVersionInfoName {
            get {
                return ResourceManager.GetString("CentralVersionInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is not recognized..
        /// </summary>
        internal static string CommandNotAvailableDesc {
            get {
                return ResourceManager.GetString("CommandNotAvailableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not acailable.
        /// </summary>
        internal static string CommandNotAvailableName {
            get {
                return ResourceManager.GetString("CommandNotAvailableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command was sent to central..
        /// </summary>
        internal static string CommonAnswerDesc {
            get {
                return ResourceManager.GetString("CommonAnswerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common answer.
        /// </summary>
        internal static string CommonAnswerName {
            get {
                return ResourceManager.GetString("CommonAnswerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common information about a locomotive..
        /// </summary>
        internal static string CommonLocomotiveInfoDesc {
            get {
                return ResourceManager.GetString("CommonLocomotiveInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common locomotive info.
        /// </summary>
        internal static string CommonLocomotiveInfoName {
            get {
                return ResourceManager.GetString("CommonLocomotiveInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error eccoured while sending a command to the central.
        /// </summary>
        internal static string ErrorSendingDesc {
            get {
                return ResourceManager.GetString("ErrorSendingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending command to central.
        /// </summary>
        internal static string ErrorSendingName {
            get {
                return ResourceManager.GetString("ErrorSendingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While receiving a command the central registered an error..
        /// </summary>
        internal static string ErrorUnknownDesc {
            get {
                return ResourceManager.GetString("ErrorUnknownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central error while receiving command.
        /// </summary>
        internal static string ErrorUnknownName {
            get {
                return ResourceManager.GetString("ErrorUnknownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains address of LI-USB-interface..
        /// </summary>
        internal static string LIAddressInfoDesc {
            get {
                return ResourceManager.GetString("LIAddressInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress of interface.
        /// </summary>
        internal static string LIAddressInfoName {
            get {
                return ResourceManager.GetString("LIAddressInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the version info about the LI-USB-interface..
        /// </summary>
        internal static string LIVersionInfoDesc {
            get {
                return ResourceManager.GetString("LIVersionInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of LI-USB-Interface..
        /// </summary>
        internal static string LIVersionInfoName {
            get {
                return ResourceManager.GetString("LIVersionInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains switch states of locomotive functions F13 to F28..
        /// </summary>
        internal static string LocomotiveFunctionStateExtDesc {
            get {
                return ResourceManager.GetString("LocomotiveFunctionStateExtDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive function state F13 to F28.
        /// </summary>
        internal static string LocomotiveFunctionStateExtName {
            get {
                return ResourceManager.GetString("LocomotiveFunctionStateExtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains type of locomotive functions F13 to F28..
        /// </summary>
        internal static string LocomotiveFunctionTypeHiDesc {
            get {
                return ResourceManager.GetString("LocomotiveFunctionTypeHiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive function type F13 to F28.
        /// </summary>
        internal static string LocomotiveFunctionTypeHiName {
            get {
                return ResourceManager.GetString("LocomotiveFunctionTypeHiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains type of locomotive functions F0 to F12..
        /// </summary>
        internal static string LocomotiveFunctionTypeLoDesc {
            get {
                return ResourceManager.GetString("LocomotiveFunctionTypeLoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive function type F0 to F12.
        /// </summary>
        internal static string LocomotiveFunctionTypeLoName {
            get {
                return ResourceManager.GetString("LocomotiveFunctionTypeLoName", resourceCulture);
            }
        }
    }
}
