//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.XpressNetLi.Comunication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flake.MoBa.XpressNetLi.Comunication.Resources.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the locomotive drive with given speed in given direction..
        /// </summary>
        internal static string DriveCommandDesc {
            get {
                return ResourceManager.GetString("DriveCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive drive command.
        /// </summary>
        internal static string DriveCommandName {
            get {
                return ResourceManager.GetString("DriveCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting central state info..
        /// </summary>
        internal static string GetCentralStateInfoDesc {
            get {
                return ResourceManager.GetString("GetCentralStateInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get central state info.
        /// </summary>
        internal static string GetCentralStateInfoName {
            get {
                return ResourceManager.GetString("GetCentralStateInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting central version info..
        /// </summary>
        internal static string GetCentralVersionDesc {
            get {
                return ResourceManager.GetString("GetCentralVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get central version.
        /// </summary>
        internal static string GetCentralVersionName {
            get {
                return ResourceManager.GetString("GetCentralVersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch adress of LI-USB-interface..
        /// </summary>
        internal static string GetLIUSBAddressDesc {
            get {
                return ResourceManager.GetString("GetLIUSBAddressDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get LI-USB address.
        /// </summary>
        internal static string GetLIUSBAddressName {
            get {
                return ResourceManager.GetString("GetLIUSBAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch version info about LI-USB interface..
        /// </summary>
        internal static string GetLIUSBVersionDesc {
            get {
                return ResourceManager.GetString("GetLIUSBVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get LI-USB version.
        /// </summary>
        internal static string GetLIUSBVersionName {
            get {
                return ResourceManager.GetString("GetLIUSBVersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the switch state of function F13 to F28..
        /// </summary>
        internal static string GetLocomotiveFunctionStateDesc {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionStateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get locomotive function switch state.
        /// </summary>
        internal static string GetLocomotiveFunctionStateName {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the type (switch or tap) of the functions F13 to F28 of a locomotive..
        /// </summary>
        internal static string GetLocomotiveFunctionTypesHidesc {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionTypesHidesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get locomotive function type (F13 to F28).
        /// </summary>
        internal static string GetLocomotiveFunctionTypesHiName {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionTypesHiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the type (switch or tap) of the first 13 functions of a locomotive..
        /// </summary>
        internal static string GetLocomotiveFunctionTypesLoDesc {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionTypesLoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get locomotive function type (F0 to F12).
        /// </summary>
        internal static string GetLocomotiveFunctionTypesLoName {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionTypesLoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting information about locomotive..
        /// </summary>
        internal static string GetLocomotiveInfoDesc {
            get {
                return ResourceManager.GetString("GetLocomotiveInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get locomotive info.
        /// </summary>
        internal static string GetLocomotiveInfoName {
            get {
                return ResourceManager.GetString("GetLocomotiveInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the start mode of the central.
        /// </summary>
        internal static string SetLCentralStartModeDesc {
            get {
                return ResourceManager.GetString("SetLCentralStartModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set central start mode.
        /// </summary>
        internal static string SetLCentralStartModeName {
            get {
                return ResourceManager.GetString("SetLCentralStartModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the refresh mode for functions of a locomotive.
        /// </summary>
        internal static string SetLFunctionRefreshModeDesc {
            get {
                return ResourceManager.GetString("SetLFunctionRefreshModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set function refresh mode.
        /// </summary>
        internal static string SetLFunctionRefreshModeName {
            get {
                return ResourceManager.GetString("SetLFunctionRefreshModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the address of th interface..
        /// </summary>
        internal static string SetLIUSBAddressDesc {
            get {
                return ResourceManager.GetString("SetLIUSBAddressDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ste LI-UBS address.
        /// </summary>
        internal static string SetLIUSBAddressName {
            get {
                return ResourceManager.GetString("SetLIUSBAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a function of a locomotive..
        /// </summary>
        internal static string SetLocomotiveFunctionDesc {
            get {
                return ResourceManager.GetString("SetLocomotiveFunctionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set locomotive function.
        /// </summary>
        internal static string SetLocomotiveFunctionName {
            get {
                return ResourceManager.GetString("SetLocomotiveFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the function type of a locomotive function..
        /// </summary>
        internal static string SetLocomotiveFunctionTypeDesc {
            get {
                return ResourceManager.GetString("SetLocomotiveFunctionTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set function type.
        /// </summary>
        internal static string SetLocomotiveFunctionTypeName {
            get {
                return ResourceManager.GetString("SetLocomotiveFunctionTypeName", resourceCulture);
            }
        }
    }
}
