//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.XpressNetLi.Comunication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlakeComunicationMsgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlakeComunicationMsgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flake.MoBa.XpressNetLi.Comunication.Resources.FlakeComunicationMsgs", typeof(FlakeComunicationMsgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general start signal was toggled..
        /// </summary>
        internal static string AllOnSet {
            get {
                return ResourceManager.GetString("AllOnSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central state: emergency stop: &apos;{0}&apos; - emergency off: &apos;{1}&apos; - central start mode: &apos;{2}&apos; - program mode active: &apos;{3}&apos; - cold start: &apos;{4}&apos; - ram check error: &apos;{5}&apos;..
        /// </summary>
        internal static string CentralStateInfo {
            get {
                return ResourceManager.GetString("CentralStateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central software version: &apos;{0}&apos; - Central type: &apos;{1}&apos;..
        /// </summary>
        internal static string CentralVersionInfo {
            get {
                return ResourceManager.GetString("CentralVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An emergency off was toggled..
        /// </summary>
        internal static string EmergencyOffToggle {
            get {
                return ResourceManager.GetString("EmergencyOffToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anemergency stop was toggled..
        /// </summary>
        internal static string EmergencyStopToggle {
            get {
                return ResourceManager.GetString("EmergencyStopToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given function number was either too large, or too small..
        /// </summary>
        internal static string ErrorReceivingFunctionNumber {
            get {
                return ResourceManager.GetString("ErrorReceivingFunctionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LI-USB-interface version: &apos;{0}&apos; - LI-UBS-interface codenumber: &apos;{1}&apos; - LI-UBS-interface address: &apos;{2}&apos;.
        /// </summary>
        internal static string LIInfoandAddress {
            get {
                return ResourceManager.GetString("LIInfoandAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given locomotive speed was out of range (too high)..
        /// </summary>
        internal static string LocomotiveSpeedTooHighForCalc {
            get {
                return ResourceManager.GetString("LocomotiveSpeedTooHighForCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given locomotive speed was out of range (too low)..
        /// </summary>
        internal static string LocomotiveSpeedTooLowForCalc {
            get {
                return ResourceManager.GetString("LocomotiveSpeedTooLowForCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The central type was not recognized..
        /// </summary>
        internal static string NotRecognizedCentralType {
            get {
                return ResourceManager.GetString("NotRecognizedCentralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given speed section value is not supported..
        /// </summary>
        internal static string NotSupportetSpeedSections {
            get {
                return ResourceManager.GetString("NotSupportetSpeedSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given direction is not supported..
        /// </summary>
        internal static string NutSupportetDirection {
            get {
                return ResourceManager.GetString("NutSupportetDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Central was switched to programming mode..
        /// </summary>
        internal static string ProgrammodeToggle {
            get {
                return ResourceManager.GetString("ProgrammodeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting LI-USB-Listener on Port &apos;{0}&apos;..
        /// </summary>
        internal static string StartLIListener {
            get {
                return ResourceManager.GetString("StartLIListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function you want to switch is not registered to this locomotive..
        /// </summary>
        internal static string WarningNotRegisteredLocoFunction {
            get {
                return ResourceManager.GetString("WarningNotRegisteredLocoFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wrong address ({0}) was received from the LI interface..
        /// </summary>
        internal static string WrongLIAddressReceived {
            get {
                return ResourceManager.GetString("WrongLIAddressReceived", resourceCulture);
            }
        }
    }
}
