//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.XpressNetLi.Comunication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlakeComunicationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlakeComunicationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flake.MoBa.XpressNetLi.Comunication.Resources.FlakeComunicationErrors", typeof(FlakeComunicationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Given Address is out of Range (0-9999)..
        /// </summary>
        internal static string AddressNotInRange {
            get {
                return ResourceManager.GetString("AddressNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received answer was empty or in incorrect format..
        /// </summary>
        internal static string AnswerEmpty {
            get {
                return ResourceManager.GetString("AnswerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial port was not available..
        /// </summary>
        internal static string ComPortNotAvailable {
            get {
                return ResourceManager.GetString("ComPortNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several errors ({0}) occured while seinding a command. The process has been terminated..
        /// </summary>
        internal static string ErrorSendingCommad {
            get {
                return ResourceManager.GetString("ErrorSendingCommad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address ({0}) for interface was not correct. Please use 1 to 31..
        /// </summary>
        internal static string InterfaceAddressCouldNotBeSet {
            get {
                return ResourceManager.GetString("InterfaceAddressCouldNotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout occured while waiting for a central answer..
        /// </summary>
        internal static string LITimeout {
            get {
                return ResourceManager.GetString("LITimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The central answer was unknown!.
        /// </summary>
        internal static string UnknownAnswer {
            get {
                return ResourceManager.GetString("UnknownAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answer format: the checksum was not correct!.
        /// </summary>
        internal static string WrongAnswerFormat {
            get {
                return ResourceManager.GetString("WrongAnswerFormat", resourceCulture);
            }
        }
    }
}
