//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.XpressNetLi.Comunication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlakeComunicationAnswerLogMsgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlakeComunicationAnswerLogMsgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flake.MoBa.XpressNetLi.Comunication.Resources.FlakeComunicationAnswerLogMsgs", typeof(FlakeComunicationAnswerLogMsgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast All Locomotives Off was sent..
        /// </summary>
        internal static string BCAllLocosOff {
            get {
                return ResourceManager.GetString("BCAllLocosOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast All Off was sent..
        /// </summary>
        internal static string BCAllOff {
            get {
                return ResourceManager.GetString("BCAllOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast All On was sent..
        /// </summary>
        internal static string BCAllOn {
            get {
                return ResourceManager.GetString("BCAllOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broadcast Program Mode was sent..
        /// </summary>
        internal static string BCProgramMode {
            get {
                return ResourceManager.GetString("BCProgramMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving central state info..
        /// </summary>
        internal static string CentralStateInfo {
            get {
                return ResourceManager.GetString("CentralStateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving version of central..
        /// </summary>
        internal static string CentralVersionInfo {
            get {
                return ResourceManager.GetString("CentralVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is not recognized..
        /// </summary>
        internal static string CommandNotAvailable {
            get {
                return ResourceManager.GetString("CommandNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command was sent to central..
        /// </summary>
        internal static string CommonAnswer {
            get {
                return ResourceManager.GetString("CommonAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return information about a locomotive..
        /// </summary>
        internal static string CommonLocomotiveInfo {
            get {
                return ResourceManager.GetString("CommonLocomotiveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While sending a command a error occured (i.g. wrong header info in array)..
        /// </summary>
        internal static string ErrorSending {
            get {
                return ResourceManager.GetString("ErrorSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The central didn&apos;t understand the last command..
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving address info from LI-USB interface..
        /// </summary>
        internal static string LIAddressInfo {
            get {
                return ResourceManager.GetString("LIAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving version info about LI-interface..
        /// </summary>
        internal static string LIVersionInfo {
            get {
                return ResourceManager.GetString("LIVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving locomotive function info of functions F13 to F28..
        /// </summary>
        internal static string LocomotiveFunctionStateExt {
            get {
                return ResourceManager.GetString("LocomotiveFunctionStateExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving locomotive function type of functions F13 to F28..
        /// </summary>
        internal static string LocomotiveFunctionTypeHi {
            get {
                return ResourceManager.GetString("LocomotiveFunctionTypeHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving locomotive function type of functions F0 to F12..
        /// </summary>
        internal static string LocomotiveFunctionTypeLo {
            get {
                return ResourceManager.GetString("LocomotiveFunctionTypeLo", resourceCulture);
            }
        }
    }
}
