//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.XpressNetLi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlakeLICommandsLogMsgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlakeLICommandsLogMsgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flake.MoBa.XpressNetLi.Resources.FlakeLICommandsLogMsgs", typeof(FlakeLICommandsLogMsgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotive &apos;{0}&apos; set to speed &apos;{1}[steps]&apos; in direction &apos;{2}&apos;..
        /// </summary>
        internal static string DriveCommand {
            get {
                return ResourceManager.GetString("DriveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting the state info of central..
        /// </summary>
        internal static string GetCentralStateInfo {
            get {
                return ResourceManager.GetString("GetCentralStateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the version of the central..
        /// </summary>
        internal static string GetCentralVersion {
            get {
                return ResourceManager.GetString("GetCentralVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching address of interface..
        /// </summary>
        internal static string GetLIUSBAddress {
            get {
                return ResourceManager.GetString("GetLIUSBAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching info about interface version..
        /// </summary>
        internal static string GetLIUSBVersion {
            get {
                return ResourceManager.GetString("GetLIUSBVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting function (F13 to F28) state about locomotove &apos;{0}&apos;..
        /// </summary>
        internal static string GetLocomotiveFunctionState {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting function (F13 to F28) type about locomotove &apos;{0}&apos;..
        /// </summary>
        internal static string GetLocomotiveFunctionTypesHi {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionTypesHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting function (F0 to F12) type about locomotove &apos;{0}&apos;..
        /// </summary>
        internal static string GetLocomotiveFunctionTypesLo {
            get {
                return ResourceManager.GetString("GetLocomotiveFunctionTypesLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Info about locomotove &apos;{0}&apos;..
        /// </summary>
        internal static string GetLocomotiveInfo {
            get {
                return ResourceManager.GetString("GetLocomotiveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the startmode of the central to &apos;{0}&apos;..
        /// </summary>
        internal static string SetLCentralStartMode {
            get {
                return ResourceManager.GetString("SetLCentralStartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the refresh mode to &apos;{0}&apos; for locomotive &apos;{1}&apos;..
        /// </summary>
        internal static string SetLFunctionRefreshMode {
            get {
                return ResourceManager.GetString("SetLFunctionRefreshMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting address of interface to &apos;{0}&apos;..
        /// </summary>
        internal static string SetLIUSBAddress {
            get {
                return ResourceManager.GetString("SetLIUSBAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; of locomotive &apos;{1}&apos; gets {2}..
        /// </summary>
        internal static string SetLocomotiveFunction {
            get {
                return ResourceManager.GetString("SetLocomotiveFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting functiontype of function &apos;F{0}&apos; of locomotive &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string SetLocomotiveFunctionType {
            get {
                return ResourceManager.GetString("SetLocomotiveFunctionType", resourceCulture);
            }
        }
    }
}
