//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.Db.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikel()
        {
            this.DokumenteZuArtikeln = new HashSet<DokumenteZuArtikeln>();
            this.LinksZuArtikeln = new HashSet<LinksZuArtikeln>();
            this.Schlagworte = new HashSet<Schlagworte>();
        }
    
        public int ArtikelNid { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public string Artikelnummer { get; set; }
        public int HerstellerNid { get; set; }
    
        public virtual Hersteller Hersteller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumenteZuArtikeln> DokumenteZuArtikeln { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinksZuArtikeln> LinksZuArtikeln { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schlagworte> Schlagworte { get; set; }
    }
}
