//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.Db.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokumente()
        {
            this.DokumenteZuArtikeln = new HashSet<DokumenteZuArtikeln>();
            this.DokumenteZuHerstellern = new HashSet<DokumenteZuHerstellern>();
            this.Links = new HashSet<Links>();
        }
    
        public int DokumentNid { get; set; }
        public byte[] Dokument { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public string Mimetype { get; set; }
        public string Dateiendung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumenteZuArtikeln> DokumenteZuArtikeln { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DokumenteZuHerstellern> DokumenteZuHerstellern { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Links> Links { get; set; }
    }
}
