//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.Db.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinksZuArtikeln
    {
        public int LinkNid { get; set; }
        public int ArtikelNid { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public string Ordnungsmerkmal { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Links Links { get; set; }
    }
}
