//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.Db.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Links()
        {
            this.LinksZuArtikeln = new HashSet<LinksZuArtikeln>();
            this.LinksZuHerstellern = new HashSet<LinksZuHerstellern>();
        }
    
        public int LinkNid { get; set; }
        public string Link { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> DokumentNid { get; set; }
    
        public virtual Dokumente Dokumente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinksZuArtikeln> LinksZuArtikeln { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinksZuHerstellern> LinksZuHerstellern { get; set; }
    }
}
