//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.Db.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocomotiveDataSheets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocomotiveDataSheets()
        {
            this.Locomotives = new HashSet<Locomotives>();
        }
    
        public int LocomotiveDataSheetNid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MaxSpeed { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public string Manuafturer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locomotives> Locomotives { get; set; }
    }
}
