//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flake.MoBa.Db.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocomotiveFunctions
    {
        public int LocomotiveFunctionNid { get; set; }
        public int LocomotiveNid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int FNumber { get; set; }
        public bool Tappable { get; set; }
    
        public virtual Locomotives Locomotives { get; set; }
    }
}
